### ISSUE TITLE
"Cannot read properties of undefined (reading 'split')" shown in browser during data import

### ISSUE THREAD

**Issue by yamap55** [igz0/spotify-playback-analytics#1]
## Summary

When uploading my Spotify data, the browser displayed the following error message:

```bash
Cannot read properties of undefined (reading 'split')
```

## Spotify Data Details

- Request to Spotify: 2025-04-26 23:19
- Download available: 2025-04-30 12:12
- Filename: my_spotify_data.zip
- File size: 1.47 MB

### Structure of my_spotify_data.zip

```
C:\Users\yamap\Downloads\my_spotify_data>tree /f
フォルダー パスの一覧:  ボリューム Windows
ボリューム シリアル番号は 3C0E-9B9C です
C:.
│  index.txt
│
├─Spotify Account Data
│      DuoNewFamily.json
│      Follow.json
│      Identifiers.json
│      Identity.json
│      Inferences.json
│      Marquee.json
│      Payments.json
│      Playlist1.json
│      Read_Me_First.pdf
│      SearchQueries.json
│      StreamingHistory_music_0.json
│      StreamingHistory_music_1.json
│      StreamingHistory_podcast_0.json
│      Userdata.json
│      Wrapped2024.json
│      YourLibrary.json
│
└─Spotify Kids Account Data_1
        Follow.json
        KidsAccount.json
        Marquee.json
        Payments.json
        Playlist1.json
        Read_Me_First.pdf
        SearchQueries.json
        StreamingHistory_music_0.json
        Userdata.json
        Wrapped2024.json
        YourLibrary.json
```

## Environment

- App URL: https://spotify-playback-analytics.igz0.com/ja/dashboard
- Browser: Chrome 135.0.7049.116 (Official Build)
- OS: Windows 11 Home 24H2

## On-screen Error Message

```
エラーが発生しました
Cannot read properties of undefined (reading 'split')
```

![Image](https://github.com/user-attachments/assets/f1917dce-f03f-4c4f-b737-9b0d5050649b)

## DevTools Console Output (excerpt)

```
page-85d601a7601e0fec.js:1 ZIPファイル内のファイル一覧: Array(30)0: "Spotify Account Data/DuoNewFamily.json"1: "Spotify Account Data/Follow.json"2: "Spotify Account Data/Identifiers.json"3: "Spotify Account Data/Identity.json"4: "Spotify Account Data/Inferences.json"5: "Spotify Account Data/Marquee.json"6: "Spotify Account Data/Payments.json"7: "Spotify Account Data/Playlist1.json"8: "Spotify Account Data/SearchQueries.json"9: "Spotify Account Data/StreamingHistory_music_0.json"10: "Spotify Account Data/StreamingHistory_music_1.json"11: "Spotify Account Data/StreamingHistory_podcast_0.json"12: "Spotify Account Data/Userdata.json"13: "Spotify Account Data/Wrapped2024.json"14: "Spotify Account Data/YourLibrary.json"15: "Spotify Account Data/"16: "Spotify Account Data/Read_Me_First.pdf"17: "Spotify Kids Account Data_1/Follow.json"18: "Spotify Kids Account Data_1/KidsAccount.json"19: "Spotify Kids Account Data_1/Marquee.json"20: "Spotify Kids Account Data_1/Payments.json"21: "Spotify Kids Account Data_1/Playlist1.json"22: "Spotify Kids Account Data_1/SearchQueries.json"23: "Spotify Kids Account Data_1/StreamingHistory_music_0.json"24: "Spotify Kids Account Data_1/Userdata.json"25: "Spotify Kids Account Data_1/Wrapped2024.json"26: "Spotify Kids Account Data_1/YourLibrary.json"27: "Spotify Kids Account Data_1/"28: "Spotify Kids Account Data_1/Read_Me_First.pdf"29: "index.txt"length: 30[[Prototype]]: Array(0)
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/DuoNewFamily.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/Follow.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/Identifiers.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/Identity.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/Inferences.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/Marquee.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/Payments.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/Playlist1.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/SearchQueries.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/StreamingHistory_music_0.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: true
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/StreamingHistory_music_1.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: true
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/StreamingHistory_podcast_0.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: true
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/Userdata.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/Wrapped2024.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/YourLibrary.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/ の検証: zipEntry存在: true ディレクトリではない: false JSONファイル: false StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/Read_Me_First.pdf の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: false StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/Follow.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/KidsAccount.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/Marquee.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/Payments.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/Playlist1.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/SearchQueries.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/StreamingHistory_music_0.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: true
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/Userdata.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/Wrapped2024.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/YourLibrary.json の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: true StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/ の検証: zipEntry存在: true ディレクトリではない: false JSONファイル: false StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/Read_Me_First.pdf の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: false StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 ファイル index.txt の検証: zipEntry存在: true ディレクトリではない: true JSONファイル: false StreamingHistoryを含む: false
page-85d601a7601e0fec.js:1 処理対象のJSONファイル数: 4
page-85d601a7601e0fec.js:1 処理中のファイル: Spotify Account Data/StreamingHistory_music_0.json
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/StreamingHistory_music_0.json を正常に処理しました。エントリ数: 10000
page-85d601a7601e0fec.js:1 処理中のファイル: Spotify Account Data/StreamingHistory_music_1.json
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/StreamingHistory_music_1.json を正常に処理しました。エントリ数: 221
page-85d601a7601e0fec.js:1 処理中のファイル: Spotify Account Data/StreamingHistory_podcast_0.json
page-85d601a7601e0fec.js:1 ファイル Spotify Account Data/StreamingHistory_podcast_0.json を正常に処理しました。エントリ数: 30
page-85d601a7601e0fec.js:1 処理中のファイル: Spotify Kids Account Data_1/StreamingHistory_music_0.json
page-85d601a7601e0fec.js:1 ファイル Spotify Kids Account Data_1/StreamingHistory_music_0.json を正常に処理しました。エントリ数: 1209
page-85d601a7601e0fec.js:1 IndexedDBに11460件のトラックデータを保存します...
page-85d601a7601e0fec.js:1 11460件のトラックデータを保存しました
page-74dab86debbbca60.js:1 IndexedDBにデータが見つかりました。
page-85d601a7601e0fec.js:1 11460件のトラックデータを読み込みました
page-74dab86debbbca60.js:1 11460件のトラックデータを読み込みました
684-0949971241c62544.js:1 データの集計中にエラーが発生しました: TypeError: Cannot read properties of undefined (reading 'split')
    at 803-fa217c11cac3d428.js:1:399238
    at a (803-fa217c11cac3d428.js:1:399536)
    at d (page-74dab86debbbca60.js:1:15068)
    at page-74dab86debbbca60.js:1:17977
    at oq (4bd1b696-af0d26e110b61d45.js:1:87086)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102582)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102619)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102619)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102619)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102619)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102619)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102619)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102619)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102619)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102562)
    at um (4bd1b696-af0d26e110b61d45.js:1:102466)
    at uh (4bd1b696-af0d26e110b61d45.js:1:102619)
window.console.error @ 684-0949971241c62544.js:1

                
          
          
          
         Chrome is moving towards a new experience that allows users to choose to browse without third-party cookies.
```

I'm happy to provide the ZIP file or any other additional information if needed for debugging.

**Comment by igz0** [comment]
@yamap55 
Thank you for your detailed report!
I’ve fixed what appeared to be the bug, so could you please check if it works correctly on your end?

**Comment by yamap55** [comment]
@igz0 
Thanks for the quick fix!
Unfortunately, I'm still seeing the same error on my end.
The logs look pretty much the same, so I’ll skip posting them here for now.
As you mentioned on SNS, I’ll send you the data file via DM.

**Comment by igz0** [comment]
## Investigation Results

After investigating this issue, I've identified the root cause of the problem.

### Cause

The error `Cannot read properties of undefined (reading 'split')` occurs because the **Extended Streaming History** option was not selected when downloading Spotify data.

There are differences in the JSON file structure between regular Spotify data exports and Extended Streaming History:

### Solution

When requesting your Spotify data, please make sure to select the "Extended Streaming History" option.

#### How to request Spotify data correctly:

1. Go to your [Spotify Account Page](https://www.spotify.com/account/privacy/)
2. In the "Privacy settings" section, select "Download a copy of your personal data"
3. **Important**: Check the "Extended Streaming History" option in the "Include additional data" section
4. Submit your request and wait for the data to become available via email

### Additional Information

Spotify data exports can have different formats depending on when and how they were requested. This application will be improved to handle various data formats in future updates.

Thank you for reporting this issue!
